apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-apps
spec:
  generators:
    - git:
        repoURL: https://github.com/AllaouaA/labs-argocd.git
        revision: HEAD
        files:
          - path: "appset/apps-config/**/config.json"
  template:
    metadata:
      name: '{{myapp.name}}'
    spec:
      project: '{{myapp.project}}'
      source:
        repoURL: https://github.com/AllaouaA/labs-argocd.git
        targetRevision: master
        path: 'demo/helm'
        helm:
          valueFiles:
            - values-{{k8s_cluster.name}}.yaml
      destination:
        server: '{{k8s_cluster.address}}'
        namespace: '{{myapp.namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated: # enable auto sync (by default is disabled)
          selfHeal: true # Undo/override any manual changes to the cluster
          prune: true # if a component is deleted/renamed on the yaml file, argocd will also delete it